---
abstract: 'coveralls backend for Devel::Cover'
author:
  - 'Kan Fushihara <kan.fushihara@gmail.com>'
build_requires:
  FindBin: '0'
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Cover-Report-Coveralls
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Devel::Cover::Report::Coveralls:
    file: lib/Devel/Cover/Report/Coveralls.pm
    version: '0.08'
requires:
  Devel::Cover: '1.02'
  Furl: '0'
  IO::Socket::SSL: '0'
  JSON::PP: '0'
  YAML: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/kan/coveralls-perl/issues
  homepage: https://github.com/kan/coveralls-perl
  repository: git://github.com/kan/coveralls-perl.git
version: '0.08'
x_contributors:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Graham Knop <haarg@haarg.org>'
